CC = gcc-4.2
CFLAGS = -Wall

.PHONY: clean

INCDRS = -I$(PRACTICE_TOPDIR)/list
SRCFLS = $(PRACTICE_TOPDIR)/list/list.c

%.o: %.c 
	$(CC) -c $(CFLAGS) $(INCDRS) -o $@ $<

all:
	make depend

depend:
	makedepend $(INCDRS) $(SRCFLS)

clean:
	rm *.o
# DO NOT DELETE

/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/assert.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/sys/cdefs.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/sys/_symbol_aliasing.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/sys/_posix_availability.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/stdlib.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/Availability.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/AvailabilityInternal.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/_types.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/sys/_types.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/machine/_types.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/i386/_types.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/sys/wait.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/sys/signal.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/sys/appleapiopts.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/machine/signal.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/i386/signal.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/i386/_structs.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/sys/_structs.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/machine/_structs.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/sys/resource.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/machine/endian.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/i386/endian.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/sys/_endian.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/libkern/_OSByteOrder.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/libkern/i386/_OSByteOrder.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/alloca.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/machine/types.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/i386/types.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/stdio.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/secure/_stdio.h
/Users/shichao/Documents/projects/practice/list/list.o: /usr/include/secure/_common.h
/Users/shichao/Documents/projects/practice/list/list.o: /Users/shichao/Documents/projects/practice/list/list.h
